import Head from 'next/head'
import Image from 'next/image'
import { useTranslations } from 'next-intl'
import { useRouter } from 'next/router'
import Code from '../components/Code'
import styles from '../styles/Home.module.css'
import PageLayout from '../components/PageLayout'


export default function Home() {
  const t = useTranslations('Index')
  const { locale } = useRouter()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <PageLayout title={t('title')}>
        <p>
          {t('description', {
            locale,
            code: (children) => <Code>{children}</Code>,
          })}
        </p>
      </PageLayout>

        
      </main>
    </>
  )
}

export function getStaticProps({ locale }: any) {
  return {
    props: {
      messages: {
        ...require(`../messages/shared/${locale}.json`),
        ...require(`../messages/index/${locale}.json`),
      },
    },
  }
}